hash-format = "sha256"

[[files]]
file = "mods/.index/advancement-locator.pw.toml"
hash = "c722992b574b0ae9126c5f439587664443a5be694d40ba19d93eae7d87ee8753"
alias = "mods/cta-1.12.2-1.2.2.jar"
metafile = true

[[files]]
file = "mods/.index/advancement-plaques.pw.toml"
hash = "10997b721cb73fe8ab34e9b398d65786befdabfda2fa374bc9f168bc44aa2438"
alias = "mods/AdvancementPlaques-1.12.2-1.4.10.jar"
metafile = true

[[files]]
file = "mods/.index/alfheim-lighting-engine.pw.toml"
hash = "719f695578b6f8db98b0b1d9b8223058cdb05ce40c47d79f7978be67f763230d"
alias = "mods/Alfheim-1.6.jar"
metafile = true

[[files]]
file = "mods/.index/antique-armory.pw.toml"
hash = "33af3cc40b77e9702676cdd222c485440856672cf6c5c5eeb673a1c51d496b8c"
alias = "mods/AntiqueArmory-1.12.2-1.2.9.jar"
metafile = true

[[files]]
file = "mods/.index/aqua-acrobatics.pw.toml"
hash = "a55ef084ef83bbc9ceb2c29af6f9820159d9d77e856b6d3bde81ac4d315ba3b3"
alias = "mods/AquaAcrobatics-1.15.4.jar"
metafile = true

[[files]]
file = "mods/.index/bansoukou.pw.toml"
hash = "fb27b8f2cbd70c1fcb4fff503db09a0ca9b9928e318a55e23607762cd7aaece4"
alias = "mods/!bansoukou-6.2.0.jar"
metafile = true

[[files]]
file = "mods/.index/base.pw.toml"
hash = "23ab9ff513e29e51c281017953cafe5ace7c5c93e7522eb5c5ce66de80265f52"
alias = "mods/base-1.12.2-3.14.0.jar"
metafile = true

[[files]]
file = "mods/.index/biomes-o-plenty.pw.toml"
hash = "9a230c152b3d7442cad0c80d5f0dafc7ade6a0789b0c12463360cbcbd3d5e16c"
alias = "mods/BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar"
metafile = true

[[files]]
file = "mods/.index/bookworm.pw.toml"
hash = "ad9b7e68a8c09f791c914ca779639a38509c1bfe826113e63cb4b342fc5259f5"
alias = "mods/bookworm-1.12.2-2.5.2.1.jar"
metafile = true

[[files]]
file = "mods/.index/bubbles-a-baubles-fork.pw.toml"
hash = "c90eb5d8bba3a8b98172eb02874611cd13d5df5dba3346b3fe8fc2e4f77ef0eb"
alias = "mods/Bubbles-2.4.10.jar"
metafile = true

[[files]]
file = "mods/.index/chibi.pw.toml"
hash = "40db0174ae2fad7ff8658b4e75f3a9b0ccb5f8d35819f7c2b9c3bfbeea317f2a"
alias = "mods/loliasm-5.33.jar"
metafile = true

[[files]]
file = "mods/.index/classic-bar-legacy.pw.toml"
hash = "d4a1b468f3e4782a20d0d0b4db280cbf4ec037aa806fceb31f77e8317cdd126c"
alias = "mods/classicbar-0.6.0.jar"
metafile = true

[[files]]
file = "mods/.index/coloured-tooltips.pw.toml"
hash = "9a9d406b26153b1a6b69cb23daa77039eced7b17c5af0d465626f17da992ee74"
alias = "mods/ColouredTooltips-1.12.2-1.0.9.jar"
metafile = true

[[files]]
file = "mods/.index/configanytime.pw.toml"
hash = "cfbf3b192645f680cad3aeb8a65168a1f1282cd2380eb97540f19e3887807cb9"
alias = "mods/!configanytime-3.0.jar"
metafile = true

[[files]]
file = "mods/.index/contenttweaker.pw.toml"
hash = "e9f1a7585e16dfbbacc6c18b452d567a8b099b817f09729c4acbc47d1be1b51b"
alias = "mods/ContentTweaker-1.12.2-4.10.0.jar"
metafile = true

[[files]]
file = "mods/.index/crafttweaker.pw.toml"
hash = "af1dda879f1af926003449e94045ca47341b3f8b765d5f3ad63818824e01f89b"
alias = "mods/CraftTweaker2-1.12-4.1.20.715.jar"
metafile = true

[[files]]
file = "mods/.index/crafttweakeradditions.pw.toml"
hash = "11fd0de6a4a03a813f1143d01e8822513097b5cf0815d5c8e6a4cbff1a0a01ad"
alias = "mods/crtadd-1.7.0.jar"
metafile = true

[[files]]
file = "mods/.index/cyclops-core.pw.toml"
hash = "1440e7f57716a4d8b4716a25065397f4f0a9941674fc5a67109d58c5ceacb3fc"
alias = "mods/CyclopsCore-1.12.2-1.6.7.jar"
metafile = true

[[files]]
file = "mods/.index/default-world-generator-ssp.pw.toml"
hash = "5dac5351211563286377e362087d30dd15cbb1f837c139d081877168e2cc6873"
alias = "mods/DefaultWorldGenerator-port-1.12-2.3.1.jar"
metafile = true

[[files]]
file = "mods/.index/dtbop.pw.toml"
hash = "2ca63a846c03308aafa361de78386c8598200e0ac4f41da5b3754962fc52eafe"
alias = "mods/DynamicTreesBOP-1.12.2-1.5.2.jar"
metafile = true

[[files]]
file = "mods/.index/dynamictrees.pw.toml"
hash = "4f1722ec2fb6098c87ee492f12278b3f16db25340d515157632f62545d77f66c"
alias = "mods/DynamicTrees-1.12.2-0.9.29.jar"
metafile = true

[[files]]
file = "mods/.index/equipment-tooltips.pw.toml"
hash = "a9622e32a8739e0c8c619363adeabbeb2474c97320282afdc3133c3c4c5c4c67"
alias = "mods/EquipmentTooltips-1.12.2-1.0.3-4.jar"
metafile = true

[[files]]
file = "mods/.index/everlastingabilities.pw.toml"
hash = "5e2ce31833e21165cb65209d1f87fe8135cc0cce36399b2e4aa5f64569616d26"
alias = "mods/EverlastingAbilities-1.12.2-1.5.3.jar"
metafile = true

[[files]]
file = "mods/.index/farmers-delight-legacy.pw.toml"
hash = "5bd6179a6a92ea704aa52a10c63cad2936a21c0885324bc89e13c1811a7a5cc9"
alias = "mods/FarmersDelightLegacy-1.1.0.jar"
metafile = true

[[files]]
file = "mods/.index/fermiumbooter2mixinbooter.pw.toml"
hash = "0111979fdc1d551facba82adca186193744e110d860b88532a912c4c22abe7bf"
alias = "mods/`fermiumbooter-1.3.13.jar"
metafile = true

[[files]]
file = "mods/.index/flexipause.pw.toml"
hash = "17446ba0139411fb280f30091a7f1f9bf9d49bfb7697a8f60538b1ebc054c12f"
alias = "mods/FlexiPause-1.1.jar"
metafile = true

[[files]]
file = "mods/.index/fluidlogged-api.pw.toml"
hash = "f2e618d33d173fc2f39c4d174d3a602317199e9343013968e7b85dc031a7f3f8"
alias = "mods/Fluidlogged-API-v3.3.2-mc1.12.2.jar"
metafile = true

[[files]]
file = "mods/.index/forgelin-continuous.pw.toml"
hash = "f8d644f42aa4785f7286269ad88cade05334fda08947658a9db4b31afe15f75f"
alias = "mods/Forgelin-Continuous-2.4.0.0.jar"
metafile = true

[[files]]
file = "mods/.index/gnetum.pw.toml"
hash = "d5d0ede5e3c4c6a368fc778b9ef966510ce2d817beab108d10cf5564abf52f2d"
alias = "mods/gnetum-1.4.3.jar"
metafile = true

[[files]]
file = "mods/.index/greenery.pw.toml"
hash = "f333c5741887e9fa5670d4ac2d3658a4ef2e7eb54e421fc8623b8aaa0029aa4e"
alias = "mods/Greenery-1.12.2-9.0.jar"
metafile = true

[[files]]
file = "mods/.index/had-enough-characters.pw.toml"
hash = "5ad629d1a2a04b415653c67e3d0b396f1df9e886eaa7233e87bde1c80917e9b1"
alias = "mods/hecharacters-1.12.2-1.4.1.jar"
metafile = true

[[files]]
file = "mods/.index/had-enough-items.pw.toml"
hash = "aa6d0fdfecfaa094a24c3d54560e0eeb44aaf0e88b29abd06a1382f9d93b077c"
alias = "mods/HadEnoughItems_1.12.2-4.31.2.jar"
metafile = true

[[files]]
file = "mods/.index/hide-key-binding.pw.toml"
hash = "6ff5badefc8508977469a6567fcb510a196a43d5548e4b0080ea2b587fd36398"
alias = "mods/[MC-1.12.2] Hide Key Binding v1.0.0.4 - 2024-12-15.jar"
metafile = true

[[files]]
file = "mods/.index/inventory-bogosorter.pw.toml"
hash = "3f205b8c37de76aa0b3a95268638020d0b3ce2abcaddfb2a752c9cb6612bf84f"
alias = "mods/bogosorter-1.6.4.jar"
metafile = true

[[files]]
file = "mods/.index/just-a-few-fish.pw.toml"
hash = "e01ddffd379ba37202da69d98cc0c278c2ab859d83fbb27218b1c7c481644415"
alias = "mods/JustAFewFish-1.7_for_1.12.jar"
metafile = true

[[files]]
file = "mods/.index/just-enough-characters.pw.toml"
hash = "659ece1c437e2747f24f0aa0296e0ce8c17f58b063c67b1e92f6174d846d4a95"
alias = "mods/jecharacters-1.12.0-3.7.3.jar"
metafile = true

[[files]]
file = "mods/.index/key-binding-patch.pw.toml"
hash = "ef99493d7c0fb9d8f15694e99c6f2fc5758cc23cdc6b54b795e592010d50e1d6"
alias = "mods/[MC-1.12.2] Key Binding Patch v1.3.3.3 - 2024-12-1.jar"
metafile = true

[[files]]
file = "mods/.index/keyboard-wizard-ce.pw.toml"
hash = "8f230d6267378191ca966b1f6e7e00711fcb1f3ffe96d9e32ee8c9fb05ebb088"
alias = "mods/keyboard-wizard-ce-forge-1.12.2-1.0.2-beta.jar"
metafile = true

[[files]]
file = "mods/.index/lemonskin.pw.toml"
hash = "da23373211de62e9988c2a0da23278e9d1a3c74d4b49c59be0989f3c2799f082"
alias = "mods/lemonskin-4.0.0.jar"
metafile = true

[[files]]
file = "mods/.index/loading-progress-bar.pw.toml"
hash = "f4854fbe2ff1ff6abb06928b70dbd598dd4eae430be3038495716f065959938a"
alias = "mods/Loading-Progress-Bar-v1.0-mc[1.8-1.12.2].jar"
metafile = true

[[files]]
file = "mods/.index/loot-beams-retro.pw.toml"
hash = "62a3344c98ee39437821359f53a78f17a9da49675630b9a2b3dd0e66ff3b93cf"
alias = "mods/lootbeamsretro-1.2.1.jar"
metafile = true

[[files]]
file = "mods/.index/mantle.pw.toml"
hash = "3e7416b42e5bb0a11ffed0fa7ecfee7a4f23b70b8d6920b62f462d08b3ec1657"
alias = "mods/Mantle-1.12-1.3.3.55.jar"
metafile = true

[[files]]
file = "mods/.index/minecraft-comes-alive-reforged.pw.toml"
hash = "b50fd718bed392322d99b6c871454105a047386e3f79689d0d24f27e54d7a403"
alias = "mods/mca-6.3.1.6.jar"
metafile = true

[[files]]
file = "mods/.index/misctweaks_.pw.toml"
hash = "37e73c2dcff4606425bfdcb93273f170a9821aa63b1f3ae168702213e296291b"
alias = "mods/MiscTweaks-1.12.2-1.5.0.jar"
metafile = true

[[files]]
file = "mods/.index/mixin-booter.pw.toml"
hash = "8c83864a67575987ff9f6c5b0ea946c4446e9f08c0eef65af30cd52c3546fb06"
alias = "mods/!mixinbooter-10.7.jar"
metafile = true

[[files]]
file = "mods/.index/modularui.pw.toml"
hash = "1d6bdfe6296b0f9b003337b67374c91489214aaf805bed46f9337cedefc6999d"
alias = "mods/modularui-3.1.6.jar"
metafile = true

[[files]]
file = "mods/.index/mouse-tweaks-unofficial.pw.toml"
hash = "bb70e4b7ed3e6723ecddd7f015a2434c00d81cb30f8461ffc75fb0b2bf703230"
alias = "mods/mousetweaks-1.12.2-3.1.5.jar"
metafile = true

[[files]]
file = "mods/.index/natures-compass.pw.toml"
hash = "1883fa6343c9b6087061b30f8e9749b006b32e4b179b961efedab688bcef7afa"
alias = "mods/NaturesCompass-1.12.2-1.8.5.jar"
metafile = true

[[files]]
file = "mods/.index/naughthirium.pw.toml"
hash = "7573566301ebb1864782ea134ba824e763c01b182258df4a58d735cd9c2cdfa7"
alias = "mods/naughthirium-2.3.0.jar"
metafile = true

[[files]]
file = "mods/.index/neverenoughanimation.pw.toml"
hash = "0f8c0c5a5fce6c2f732469ba0e046006aded0caed8ad2c9ffe1a63a674629e7b"
alias = "mods/neverenoughanimations-1.0.7.jar"
metafile = true

[[files]]
file = "mods/.index/nothirium.pw.toml"
hash = "b9e014cbf22fda19f5d21372425311ed585382dd67bc8d6a4bd9a659d89faa57"
alias = "mods/Nothirium-1.12.2-0.4.9-beta.jar"
metafile = true

[[files]]
file = "mods/.index/nutrition-unofficial-extended-life.pw.toml"
hash = "d9988f4b896f7f6bec2efa23eca1cc314852e29499be2fa907e142fb879fffed"
alias = "mods/Nutrition-UEL-4.16.0.jar"
metafile = true

[[files]]
file = "mods/.index/only-crates.pw.toml"
hash = "b2247e8f98b612a4fbd874c19acab717228708e23cbe4dcb10e7fb5fd087cd76"
alias = "mods/onlycrates-1.0.0.jar"
metafile = true

[[files]]
file = "mods/.index/optinotfine.pw.toml"
hash = "3868300dbce5141e8538fcc60fe54cfabeadf1195244418bc454709775ebe810"
alias = "mods/OptiNotFine-1.0.jar"
metafile = true

[[files]]
file = "mods/.index/ore-excavation.pw.toml"
hash = "89109d99ca86e76274581f08daad40cf44efd5cbb5067c03ad0f8c5a6b05cb1f"
alias = "mods/OreExcavation-1.4.150.jar"
metafile = true

[[files]]
file = "mods/.index/oreexcavation-integration.pw.toml"
hash = "815dac4c538254cfd56dcc52cab197330530d96ae3484072cf4db8ff914b6f75"
alias = "mods/oeintegration-2.3.4.jar"
metafile = true

[[files]]
file = "mods/.index/packet-fixer.pw.toml"
hash = "b79d55edbcf4c253b3834e812aeda976798bf13cc6572a890a16d71d24f57072"
alias = "mods/PacketFixer-forge-2.1.0-1.12.2.jar"
metafile = true

[[files]]
file = "mods/.index/projecte.pw.toml"
hash = "9239b124f36eac693e812265dbace6a32d65d080bf31843d02e58ad6e1442163"
alias = "mods/ProjectE-1.12.2-PE1.4.1.jar"
metafile = true

[[files]]
file = "mods/.index/projectex.pw.toml"
hash = "5e1bdf0098fa179f040717a2817be361f819a1fb9d14e1dc096a98c7ace004d6"
alias = "mods/ProjectEX-1.2.0.40.jar"
metafile = true

[[files]]
file = "mods/.index/realistic-terrain-generation-community.pw.toml"
hash = "d6ff346ee0829aee99cf32e59e0f887d332093c1b30da99f6049bad5399a2ee6"
alias = "mods/rtgc-1.0.7.jar"
metafile = true

[[files]]
file = "mods/.index/red-core.pw.toml"
hash = "76eda7c7459df10afb8ef0ec6e7da9230abe6a2594b94965cfc644aa3464969d"
alias = "mods/!Red-Core-MC-1.8-1.12-0.7.1.jar"
metafile = true

[[files]]
file = "mods/.index/reid.pw.toml"
hash = "394731a492e9d5fb2cdcb2615329e7c36ca02a890723729735f450d5f1671bc7"
alias = "mods/RoughlyEnoughIDs-2.3.1.jar"
metafile = true

[[files]]
file = "mods/.index/renderlib.pw.toml"
hash = "850f9c1f7c68fea5ec98da74afd31dc42ef44d390c7c459992431f5c6b0e8a56"
alias = "mods/RenderLib-1.12.2-1.4.5.jar"
metafile = true

[[files]]
file = "mods/.index/resource-loader.pw.toml"
hash = "e37d9ce2b0adbb8161e9c68fdc5d188f376e485768680b26d8b3a2ca6628c7b4"
alias = "mods/ResourceLoader-MC1.12.1-1.5.3.jar"
metafile = true

[[files]]
file = "mods/.index/resource-mod-loader.pw.toml"
hash = "402d9c107d1d6cd0a5cbd331c3cfbde65bfbfa2b68a642f3570b3fc7202d9b29"
alias = "mods/ResourceModLoader-snapshot-79.jar"
metafile = true

[[files]]
file = "mods/.index/rlfoliage.pw.toml"
hash = "7e997a3f8e6f146c86c350eac547db7c7bd35b03a27451b9a895cda892120aa7"
alias = "mods/RLFoliage-MC1.12-2.5.3.jar"
metafile = true

[[files]]
file = "mods/.index/roid-tweaker.pw.toml"
hash = "c3eb6fc0edd56f5677cf95f21cd3ea7553a2962d8f0f67839f1171433a74e2f4"
alias = "mods/roidtweaker-1.3.1.jar"
metafile = true

[[files]]
file = "mods/.index/simple-storage-network.pw.toml"
hash = "df6f80d53a34a87ce9c000ca1c02482767946157512a23a4e192ffd7693074ad"
alias = "mods/SimpleStorageNetwork-1.12.2-2.0.0.jar"
metafile = true

[[files]]
file = "mods/.index/stellarcore.pw.toml"
hash = "70528f45cd2d9c2bdb3efbd4f9627a2e9f796df48db677cc556d306f28336fc4"
alias = "mods/StellarCore-1.5.22.jar"
metafile = true

[[files]]
file = "mods/.index/the-birdwatching-mod.pw.toml"
hash = "8e78067caadcb23db29249dba689ddd0c0391914ee3377fb8d57ff430f370304"
alias = "mods/TheBirdwatchingMod-1.6.0.jar"
metafile = true

[[files]]
file = "mods/.index/the-one-probe-community-edition.pw.toml"
hash = "9b7044830076b1234283f55bab6d38765b7011f565a6598a2930007973a465f8"
alias = "mods/TheOneProbe-CE-1.12-1.3.7-fix1.jar"
metafile = true

[[files]]
file = "mods/.index/tinkers-antique.pw.toml"
hash = "08ca6dd16e14e38ab993b694f3477052de0ee5bb9965fd3800e728c838638f8b"
alias = "mods/TinkersAntique-1.12.2-2.13.0.207.jar"
metafile = true

[[files]]
file = "mods/.index/tinkers-planner-antique.pw.toml"
hash = "43490f4f7c673dd68ebc27d713b148cef5400ca73a6f88abde83c8795d140ecd"
alias = "mods/TinkersPlannerAntique-1.12.2-1.0.3.jar"
metafile = true

[[files]]
file = "mods/.index/tragicmc3.pw.toml"
hash = "00e1d7cb358a7e7961da3d1b607e646db63e98d576fdb2089d68f67f28235311"
alias = "mods/TragicMC3-1.12.2-1.57.5258.jar"
metafile = true

[[files]]
file = "mods/.index/traveler-titles.pw.toml"
hash = "649b95212dd5bba5f36a611f524051d2e1c7cec68da35ff84f45eae8613ef968"
alias = "mods/TravelersTitles-1.12.2-1.1.0.jar"
metafile = true

[[files]]
file = "mods/.index/universal-tweaks.pw.toml"
hash = "855aee09f682f3ae536ecf92716a392d902dcd93ca9551ae87e5f0675864c420"
alias = "mods/UniversalTweaks-1.12.2-1.20.1.jar"
metafile = true

[[files]]
file = "mods/.index/vintagefix.pw.toml"
hash = "dd81a3ad784f688202b4179e020f5527646abbfbfd403f4b22ee02cffa03633f"
alias = "mods/vintagefix-0.7.0.jar"
metafile = true

[[files]]
file = "mods/.index/xaerolib.pw.toml"
hash = "8c15d7b56d7069090351a69d2bfee163046a75fe300ea96e68f3340fd61c54f0"
alias = "mods/xaerolib-forge-1.12.2-1.1.0.jar"
metafile = true

[[files]]
file = "mods/.index/xaeros-minimap.pw.toml"
hash = "e8f10db7d8a2e2794d9540e713e6c6a485c2262682e922bcee3261e6903fc87f"
alias = "mods/xaerominimap-forge-1.12.2-26.1.0.jar"
metafile = true

[[files]]
file = "mods/.index/xaeros-world-map.pw.toml"
hash = "10f34ec26ef5f7a60704d3cd829efb878330d59ff87efb2a9ecb031019daec03"
alias = "mods/xaeroworldmap-forge-1.12.2-1.41.2.jar"
metafile = true

[[files]]
file = "mods/.index/xp-orb-clump.pw.toml"
hash = "d14024e32b2ff3151e90983f005a4dc10deda8174281d3fef7b60ff0671cc684"
alias = "mods/Fixeroo-2.3.7.jar"
metafile = true

[[files]]
file = "mods/.index/ydms-weapon-master.pw.toml"
hash = "d6e026874ca7ec4e781686a3d309a6aa7d463c98c01c17c583eed20b9a99d65f"
alias = "mods/weaponmaster_ydm-forge-1.12.2-4.2.3.jar"
metafile = true

[[files]]
file = "mods/.index/yungs-better-caves.pw.toml"
hash = "3184c34005119b0d63ec2412224f6d19e7141c2c705d15b07155c4872796b8bb"
alias = "mods/bettercaves-1.12.2-2.0.4.jar"
metafile = true

[[files]]
file = "mods/.index/zenutil.pw.toml"
hash = "c038660495265afaa0b59655e482cd5bf66c11bbeb851fc0e677bd3aa6bdc5b7"
alias = "mods/zenutils-1.27.4.jar"
metafile = true

[[files]]
file = "mods/.index/zs-packet.pw.toml"
hash = "df24ed2edc482911dc7c729917e6a854d87d6dbd7e8afc53766257853a8dfa9f"
alias = "mods/zspacket-0.0.1.jar"
metafile = true

[[files]]
file = "resourcepacks/Minecraft-Mod-Language-Modpack.zip"
hash = "1bb8912bf1962b9effd564ba883141e54678e2329883605f8e7ae22791d20adf"

[[files]]
file = "resourcepacks/Shaggy-Grass.zip"
hash = "90fc218d093d798c6a958d99c5566d1aa0b6bd6dd4a34bad72b0b039e7e1c97b"

[[files]]
file = "resourcepacks/VM汉化组模组汉化包1.12.2.zip"
hash = "76ebad3944234d54df75a1f598c5a84156fbcdabad75f5c03dd4e1cd5c5560f4"

[[files]]
file = "resourcepacks/§d§lGlowy Nether Portals.zip"
hash = "f9edfc570cfedd16d0a3bba6f5cdbcbfea3812420b4289638fb5c4ca2ddcb811"

