name = "HymnOfHeroism"
author = "YL_kkx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c30bf546ec5baba481289d310cd791c1bc9341a16c3cd1508c408f1ee5b60c8"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
