name = "HymnOfHeroism"
author = "YL_kkx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ca23313fd2091f342ebc19de4c26f53ea5bb21484c6e8df820eb041fcf30f59"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"

[export]
[export.curseforge]
project-id = 0
